/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyButton {
    'name': string;
    'onClickHandler': Function;
  }
  interface MyClearer {
    'value': string;
  }
  interface MyComponent {
    'text': string;
  }
  interface MyInput {
    'onChangeHandler': (value: string) => void;
    'value': string;
  }
}

declare global {


  interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {}
  var HTMLMyButtonElement: {
    prototype: HTMLMyButtonElement;
    new (): HTMLMyButtonElement;
  };

  interface HTMLMyClearerElement extends Components.MyClearer, HTMLStencilElement {}
  var HTMLMyClearerElement: {
    prototype: HTMLMyClearerElement;
    new (): HTMLMyClearerElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {}
  var HTMLMyInputElement: {
    prototype: HTMLMyInputElement;
    new (): HTMLMyInputElement;
  };
  interface HTMLElementTagNameMap {
    'my-button': HTMLMyButtonElement;
    'my-clearer': HTMLMyClearerElement;
    'my-component': HTMLMyComponentElement;
    'my-input': HTMLMyInputElement;
  }
}

declare namespace LocalJSX {
  interface MyButton extends JSXBase.HTMLAttributes<HTMLMyButtonElement> {
    'name'?: string;
    'onClickHandler'?: Function;
  }
  interface MyClearer extends JSXBase.HTMLAttributes<HTMLMyClearerElement> {
    'value'?: string;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    'text'?: string;
  }
  interface MyInput extends JSXBase.HTMLAttributes<HTMLMyInputElement> {
    'onChangeHandler'?: (value: string) => void;
    'value'?: string;
  }

  interface IntrinsicElements {
    'my-button': MyButton;
    'my-clearer': MyClearer;
    'my-component': MyComponent;
    'my-input': MyInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


